### ISSUE TITLE
Support for IPv6-only ND Setup

### ISSUE THREAD

**Issue by marehler** [CiscoDevNet/ansible-nd#106]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

My customer is building a new SW-defined data center using IPv6 only. IPv6-only is mandatory for compliance with the IPv6 Master Plan for the German federal public administrations, as well as various EU regulations. This includes all management networks and tools.

Beginning with release 3.0(1), Nexus Dashboard supports pure IPv6 configurations for the cluster nodes and services. However in the current version of the nd_setup module, various IPv4 parameters are required. For IPv6-only support, IPv4 and IPv6 parameters need to become choices instead. For example, ipv4_address/ipv4_gateway only, ipv6_address/ipv6_gateway only, or both. Similar, app_network/service_network and app_network_ipv6/service_network_ipv6.

### Example

```
  - name: Set up ND
    cisco.nd.nd_setup:
      cluster_name: vND-Cluster-3
      ntp_config:
        servers:
          - ntp_host: 2a00:8a60:0:20::123
      dns_server:
        - 2001:420:464d:1::a
      app_network_ipv6: 2000::/108
      service_network_ipv6: 3000::/108
      deployment_mode:
        - ndfc
      external_services:
        management_service_ips:
          - fd00:16:1:ac::35
          - fd00:16:1:ac::36
          - fd00:16:1:ac::37
      nodes:
        - hostname: vND3-node1
          serial_number: 6BAEC7FB40CD
          username: rescue-user
          password: xxxxx
          management_network:
            ipv6_address: fd00:16:1:ac::30/64
            ipv6_gateway: fd00:16:1:ac::1
          data_network:
            ipv6_address: fd00:16:1:ad::30/64
            ipv6_gateway: fd00:16:1:ad::1
```

### New or Affected Module(s)

* nd_setup

### ND Version and ND Platform

* Version: 3.0(1), 3.1.1, 3.2.1, or higher
* Platform: all

### Collection Versions

* cisco.nd 1.2.0, 1.3.0
