### ISSUE TITLE
ND Setup fails for virtual ND with 3 Nodes (DCNE-333)

### ISSUE THREAD

**Issue by marehler** [CiscoDevNet/ansible-nd#118]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

The nd_setup modules fails to set up a virtual ND cluster with 3 nodes. The error message is misleading. Node management and data addresses are assigned correctly as shown in the output below.

The issue does not occur for a virtual ND with a single node.

### Affected Module Name(s):

* nd_setup

### ND version and ND Platform

* Version: 3.2.1
* Platform: virtual ND

### Collection versions

* cisco.nd 1.2.0, 1.3.0

### Output/ Error message

````
TASK [Set up Nexus Dashboard] ********************************************************************************************************
fatal: [marehler-vND4-node1]: FAILED! => {"changed": false, "current": {}, "data": {"clusterConfig": {"appNetwork": null, "appNetworkV6": "2000::/108", "deploymentMode": "ndfc", "externalServices": [{"pool": ["2001:420:448b:8006::44", "2001:420:448b:8006::45", "2001:420:448b:8006::46"], "target": "Management"}], "ignoreHosts": null, "name": "vND-Cluster-4", "nameServers": ["2001:420:464d:1::a"], "ntpConfig": {"keys": [], "servers": [{"host": "2001:420:448b:8006:250:56ff:fe93:76a7", "keyID": null, "prefer": false}]}, "ntpServers": null, "proxyServers": [{"password": null, "proxyURL": null, "username": null}], "searchDomains": null, "serviceNetwork": null, "serviceNetworkV6": "3000::/108"}, "nodes": [{"bgpConfig": {"as": null, "peers": null}, "dataNetwork": {"gateway": null, "gatewayv6": "fd00:16:1:ad::1", "ipSubnet": null, "ipv6Subnet": "fd00:16:1:ad::41/64", "vlan": null}, "hostName": "marehler-vND4-node1", "managementNetwork": {"gateway": null, "gatewayv6": "2001:420:448b:8006::1", "ipSubnet": null, "ipv6Subnet": "2001:420:448b:8006::41/64"}, "nodeController": {"ipAddress": "2001:420:448b:8006::41", "loginPassword": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", "loginUser": "rescue-user"}, "role": "Master", "serialNumber": "AEEF22EF861C"}, {"bgpConfig": {"as": null, "peers": null}, "dataNetwork": {"gateway": null, "gatewayv6": "fd00:16:1:ad::1", "ipSubnet": null, "ipv6Subnet": "fd00:16:1:ad::42/64", "vlan": null}, "hostName": "marehler-vND4-node2", "managementNetwork": {"gateway": null, "gatewayv6": "2001:420:448b:8006::1", "ipSubnet": null, "ipv6Subnet": "2001:420:448b:8006::42/64"}, "nodeController": {"ipAddress": "2001:420:448b:8006::42", "loginPassword": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", "loginUser": "rescue-user"}, "role": "Master", "serialNumber": "BB2C4B382911"}, {"bgpConfig": {"as": null, "peers": null}, "dataNetwork": {"gateway": null, "gatewayv6": "fd00:16:1:ad::1", "ipSubnet": null, "ipv6Subnet": "fd00:16:1:ad::43/64", "vlan": null}, "hostName": "marehler-vND4-node3", "managementNetwork": {"gateway": null, "gatewayv6": "2001:420:448b:8006::1", "ipSubnet": null, "ipv6Subnet": "2001:420:448b:8006::43/64"}, "nodeController": {"ipAddress": "2001:420:448b:8006::43", "loginPassword": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", "loginUser": "rescue-user"}, "role": "Master", "serialNumber": "263E0832FC42"}]}, "msg": "Connection failed for https://[2001:420:448b:8006::41]:443/bootstrap/cluster. OK (353 bytes)", "raw": "Bad request, error: Invalid node config for marehler-vND4-node2, error: Missing: Unsupport Node Controller : , Invalid node config for marehler-vND4-node3, error: Missing: Unsupport Node Controller : , Some or all nodes missing management IPv6 address, nodes: 3, management IPv6s: 1, Some or all nodes missing data IPv6 address, nodes: 3, data IPv6s: 1\n", "socket": "/Users/marehler/.ansible/pc/489da146ec", "status": 500}
````

### Expected Behavior

ND should be set up with 3 nodes.

### Actual Behavior

The setup fails with the error message below.

### Playbook tasks to Reproduce

````
  - name: Set up Nexus Dashboard
    cisco.nd.nd_setup:
      cluster_name: "{{ cluster_name }}"
      ntp_config:
        servers: "{{ ntp_servers }}"
      dns_server: "{{ dns_servers }}"
      app_network_ipv6: "{{ app_network_ipv6 }}"
      service_network_ipv6: "{{ service_network_ipv6 }}"
      deployment_mode:
        - ndfc
      external_services:
        management_service_ips: "{{ management_service_ips }}"
      nodes:
        - hostname: "{{ nodes.0.hostname }}"
          management_ip_address: "{{ nodes.0.management_network.ipv6_address.split('/')[0] }}"
          serial_number: "{{ serial_dict[nodes.0.hostname] }}"
          username: rescue-user
          password: "{{ lookup('ansible.builtin.env', 'RESCUE_PASSWORD') }}"
          management_network:
            ipv6_address: "{{ nodes.0.management_network.ipv6_address }}"
            ipv6_gateway: "{{ nodes.0.management_network.ipv6_gateway }}"
          data_network:
            ipv6_address: "{{ nodes.0.data_network.ipv6_address }}"
            ipv6_gateway: "{{ nodes.0.data_network.ipv6_gateway }}"
        - hostname: "{{ nodes.1.hostname }}"
          management_ip_address: "{{ nodes.1.management_network.ipv6_address.split('/')[0] }}"
          serial_number: "{{ serial_dict[nodes.1.hostname] }}"
          username: rescue-user
          password: "{{ lookup('ansible.builtin.env', 'RESCUE_PASSWORD') }}"
          management_network:
            ipv6_address: "{{ nodes.1.management_network.ipv6_address }}"
            ipv6_gateway: "{{ nodes.1.management_network.ipv6_gateway }}"
          data_network:
            ipv6_address: "{{ nodes.1.data_network.ipv6_address }}"
            ipv6_gateway: "{{ nodes.1.data_network.ipv6_gateway }}"
        - hostname: "{{ nodes.2.hostname }}"
          management_ip_address: "{{ nodes.2.management_network.ipv6_address.split('/')[0] }}"
          serial_number: "{{ serial_dict[nodes.2.hostname] }}"
          username: rescue-user
          password: "{{ lookup('ansible.builtin.env', 'RESCUE_PASSWORD') }}"
          management_network:
            ipv6_address: "{{ nodes.2.management_network.ipv6_address }}"
            ipv6_gateway: "{{ nodes.2.management_network.ipv6_gateway }}"
          data_network:
            ipv6_address: "{{ nodes.2.data_network.ipv6_address }}"
            ipv6_gateway: "{{ nodes.2.data_network.ipv6_gateway }}"
    register: setup
````

### Analysis

From comparing the API request generated via GUI with the API request generated by the ND Setup module, I found that the "id" Node Controller attribute seems to be missing.

The following code in 'nd_setup.py' fixes the issue for virtual ND deployments:

````
                    "nodeController": {
                        "id": "vnode",                                      <-- missing attribute
                        "ipAddress": node.get("management_ip_address"),
                        "loginUser": node.get("username"),
                        "loginPassword": node.get("password"),
                    },
````

However for physical deployments, the ID needs to be set to "cimc".

Output of successful setup with the above workaround:

````
TASK [Set up Nexus Dashboard] *******************************************************************************************************************************************
changed: [marehler-vND4-node1] => {"changed": true, "current": {"clusterConfig": {"appNetwork": null, "appNetworkV6": "2000::/108", "deploymentMode": "ndfc", "externalServices": [{"pool": ["2001:420:448b:8006::44", "2001:420:448b:8006::45", "2001:420:448b:8006::46"], "target": "Management"}], "ignoreHosts": null, "name": "vND-Cluster-4", "nameServers": ["2001:420:464d:1::a"], "ntpConfig": {"keys": [], "servers": [{"host": "2001:420:448b:8006:250:56ff:fe93:76a7", "keyID": null, "prefer": false}]}, "ntpServers": null, "proxyServers": [{"password": null, "proxyURL": null, "username": null}], "searchDomains": null, "serviceNetwork": null, "serviceNetworkV6": "3000::/108"}, "nodes": [{"bgpConfig": {"as": null, "peers": null}, "dataNetwork": {"gateway": null, "gatewayv6": "fd00:16:1:ad::1", "ipSubnet": null, "ipv6Subnet": "fd00:16:1:ad::41/64", "vlan": null}, "hostName": "marehler-vND4-node1", "managementNetwork": {"gateway": null, "gatewayv6": "2001:420:448b:8006::1", "ipSubnet": null, "ipv6Subnet": "2001:420:448b:8006::41/64"}, "nodeController": {"id": "vnode", "ipAddress": "2001:420:448b:8006::41", "loginPassword": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", "loginUser": "rescue-user"}, "role": "Master", "serialNumber": "630C797D29FC"}, {"bgpConfig": {"as": null, "peers": null}, "dataNetwork": {"gateway": null, "gatewayv6": "fd00:16:1:ad::1", "ipSubnet": null, "ipv6Subnet": "fd00:16:1:ad::42/64", "vlan": null}, "hostName": "marehler-vND4-node2", "managementNetwork": {"gateway": null, "gatewayv6": "2001:420:448b:8006::1", "ipSubnet": null, "ipv6Subnet": "2001:420:448b:8006::42/64"}, "nodeController": {"id": "vnode", "ipAddress": "2001:420:448b:8006::42", "loginPassword": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", "loginUser": "rescue-user"}, "role": "Master", "serialNumber": "50E056F1662F"}, {"bgpConfig": {"as": null, "peers": null}, "dataNetwork": {"gateway": null, "gatewayv6": "fd00:16:1:ad::1", "ipSubnet": null, "ipv6Subnet": "fd00:16:1:ad::43/64", "vlan": null}, "hostName": "marehler-vND4-node3", "managementNetwork": {"gateway": null, "gatewayv6": "2001:420:448b:8006::1", "ipSubnet": null, "ipv6Subnet": "2001:420:448b:8006::43/64"}, "nodeController": {"id": "vnode", "ipAddress": "2001:420:448b:8006::43", "loginPassword": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", "loginUser": "rescue-user"}, "role": "Master", "serialNumber": "BA8655B4EBF8"}]}, "data": {"clusterConfig": {"appNetwork": null, "appNetworkV6": "2000::/108", "deploymentMode": "ndfc", "externalServices": [{"pool": ["2001:420:448b:8006::44", "2001:420:448b:8006::45", "2001:420:448b:8006::46"], "target": "Management"}], "ignoreHosts": null, "name": "vND-Cluster-4", "nameServers": ["2001:420:464d:1::a"], "ntpConfig": {"keys": [], "servers": [{"host": "2001:420:448b:8006:250:56ff:fe93:76a7", "keyID": null, "prefer": false}]}, "ntpServers": null, "proxyServers": [{"password": null, "proxyURL": null, "username": null}], "searchDomains": null, "serviceNetwork": null, "serviceNetworkV6": "3000::/108"}, "nodes": [{"bgpConfig": {"as": null, "peers": null}, "dataNetwork": {"gateway": null, "gatewayv6": "fd00:16:1:ad::1", "ipSubnet": null, "ipv6Subnet": "fd00:16:1:ad::41/64", "vlan": null}, "hostName": "marehler-vND4-node1", "managementNetwork": {"gateway": null, "gatewayv6": "2001:420:448b:8006::1", "ipSubnet": null, "ipv6Subnet": "2001:420:448b:8006::41/64"}, "nodeController": {"id": "vnode", "ipAddress": "2001:420:448b:8006::41", "loginPassword": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", "loginUser": "rescue-user"}, "role": "Master", "serialNumber": "630C797D29FC"}, {"bgpConfig": {"as": null, "peers": null}, "dataNetwork": {"gateway": null, "gatewayv6": "fd00:16:1:ad::1", "ipSubnet": null, "ipv6Subnet": "fd00:16:1:ad::42/64", "vlan": null}, "hostName": "marehler-vND4-node2", "managementNetwork": {"gateway": null, "gatewayv6": "2001:420:448b:8006::1", "ipSubnet": null, "ipv6Subnet": "2001:420:448b:8006::42/64"}, "nodeController": {"id": "vnode", "ipAddress": "2001:420:448b:8006::42", "loginPassword": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", "loginUser": "rescue-user"}, "role": "Master", "serialNumber": "50E056F1662F"}, {"bgpConfig": {"as": null, "peers": null}, "dataNetwork": {"gateway": null, "gatewayv6": "fd00:16:1:ad::1", "ipSubnet": null, "ipv6Subnet": "fd00:16:1:ad::43/64", "vlan": null}, "hostName": "marehler-vND4-node3", "managementNetwork": {"gateway": null, "gatewayv6": "2001:420:448b:8006::1", "ipSubnet": null, "ipv6Subnet": "2001:420:448b:8006::43/64"}, "nodeController": {"id": "vnode", "ipAddress": "2001:420:448b:8006::43", "loginPassword": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", "loginUser": "rescue-user"}, "role": "Master", "serialNumber": "BA8655B4EBF8"}]}, "socket": "/Users/marehler/.ansible/pc/2e8074e280"}
````
