### ISSUE TITLE
Cannot specify local as login_domain

### ISSUE THREAD

**Issue by andbyrne** [CiscoDevNet/ansible-nd#14]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

* When login_domain is set to 'local', it is ignored. This presents an issue when the default authentication method in ND has been changed to something other than local.
* The nd.py explicitly sets login_domain to 'DefaultAuth', however when a cisco.nd module is called without a value for login_domain, it defaults to 'local'.

### Affected Module Name(s):

* httpapi/nd.py

### ND version and ND Platform

* V 2.1(2d) Physical

### Collection versions

* cisco.nd 0.1.2

### Output/ Error message

`fatal: [ND]: FAILED! => {"changed": false, "current": {}, "data": null, "msg": {"error": "dial tcp x.x.x.x:49: connect: connection refused", "statusCode": 500}}`

### Expected Behavior

* Code should have passed through value for login_domain as local

### Actual Behavior

* Code ignored a value of local as login_domain, and instead used DefaultAuth

### Playbook tasks to Reproduce

ND:
* Change default authentication to something other than local (e.g. TACACS)

Inventory:
```
all:
  hosts:
    ND:
      ansible_host: "x.x.x.x"
      ansible_connection: "ansible.netcommon.httpapi"
      ansible_network_os: "cisco.nd.nd"
      ansible_httpapi_validate_certs: "False"
      ansible_httpapi_use_ssl: "True"
      ansible_httpapi_use_proxy: "False"
      ansible_user: "admin"
      ansible_password: "xxxxxx"
```

Playbook:
```
- name: Nexus Dashboard
  hosts: ND
  gather_facts: no
  tasks:
    - name: Get Nexus Dashboard version
      cisco.nd.nd_version:
        login_domain: "local"
        state: query
      register: query_result

    - name: Print output
      debug:
        var: query_result
```
