### ISSUE TITLE
Support Contract Hit Stats Dump

### ISSUE THREAD

**Issue by camrossi** [CiscoDevNet/ansible-nd#30]
This issue is to track adding support to export NDI Contract Stats into a CSV File. 

Ideally we will have a task as following:
```
  tasks:
    - name: get contract stats
      cisco.nd.nd_contracts_stats: 
        insights_group: SYD
        site_name: FAB1
        hitcount_by: EpgContractFilter
        file: stats.csv
```
and will dump all the statistics in csv format. 

The use case is around contract optimisation and clean up where we can easily filter this data externally to understandf which contract are getting hit and which ones aren't so that they can be removed.
