### ISSUE TITLE
nd_pcv fails when file is XML (DCNE-150)

### ISSUE THREAD

**Issue by adealdag** [CiscoDevNet/ansible-nd#76]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Module Name(s):

* nd_pcv

### ND version and ND Platform

* NDI 6.4.1.45
* ND 3.1(1k)

### APIC version and APIC Platform for Site related issues

N/A

### Collection versions

* cisco.nd 0.5.0

### Output/ Error message

```
TASK [Creates v1 Pre-Change Analysis from file] **********************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
fatal: [nd-cx-rtp]: FAILED! => {
    "changed": false,
    "rc": 1
}
```

### Expected Behavior

* A Pre-Change Analysis job should have been submitted to ND without any previous manipulation of the file, when extension is XML.

### Actual Behavior

* Module tried to decode XML file as if it's JSON, hence producing an issue.

### Playbook tasks to Reproduce

```
- name: Creates v1 Pre-Change Analysis from file
      cisco.nd.nd_pcv:
        <<: *nd_login
        ig_name: "{{ ig_name }}"
        site_name: "{{ site_name }}"
        name: "pod{{'%02d' % pod_number}}-pca-v1"
        file: "./files/config-pca-ciscolive-lab-pod{{'%02d' % pod_number}}-v1.xml"
        state: present
```
